# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55752facca2b8568325350f420250f37"
name = "Elivide Quiz"
application_url = "https://elivide-quiz.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://elivide-quiz.fly.dev/auth/callback",
  "https://elivide-quiz.fly.dev/auth/shopify/callback",
  "https://elivide-quiz.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://elivide-quiz.fly.dev/api/proxy"
subpath = "quiz"
prefix = "apps"
